name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get public ip
        id: runner-ip
        run: curl https://ifconfig.me/ip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: gh-actions

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_NAME }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.runner-ip.outputs.ipv4 }}/32

      - name: Set up SSH key
        run: |
          echo "${{ secrets.AWS_EC2_KEYPAIR }}" > key.pem
          chmod 400 key.pem

      - name: Copy and run remote script
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no deploy/redeploy.sh ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }}:/tmp/redeploy.sh
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_PUBLIC_IP }} 'bash /tmp/redeploy.sh'

      - name: Remove Github Actions IP from Security group
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_NAME }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.runner-ip.outputs.ipv4 }}/32
