name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
      - name: Copy and run remote script
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no deploy/redeploy.sh ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/tmp/redeploy.sh
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'bash /tmp/redeploy.sh'
